version: '3.4'

#networks:
  #k6:
  #grafana:
networks:
  microservices-network:
    driver: bridge

services:

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    networks:
      - microservices-network
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=k6

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - ./loadtest/grafana/dashboards:/var/lib/grafana/dashboards
      - ./loadtest/grafana/grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./loadtest/grafana/grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
    networks:
      - microservices-network

  k6:
    image: grafana/k6:latest
    container_name: k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - .\loadtest\scripts:/scripts
    networks:
      - microservices-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: run /scripts/post_product_script.js
volumes:
  influxdb-data:
  grafana-data: